image:
  file: Dockerfile
tasks:
  - name: Startup
    command: sh ./setup/start.sh
ports:
  # Open Apache HTTP port automatically
  - port: 80
    onOpen: open-browser
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
